-- Generated by prisma migrate diff
-- WARNING: This script is intended for manual execution and review.

-- CreateEnum
CREATE TYPE "public"."ShowRole" AS ENUM ('PRODUCER', 'HOST', 'JUDGE', 'MODERATOR');

-- CreateEnum
CREATE TYPE "public"."CupStatus" AS ENUM ('DRAFT', 'SCHEDULED', 'LIVE', 'COMPLETED', 'CANCELLED');

-- CreateEnum
CREATE TYPE "public"."SeriesStatus" AS ENUM ('PLANNED', 'ACTIVE', 'COMPLETED', 'ARCHIVED');

-- AlterEnum
-- NOTE: To support PostgreSQL 11 and earlier, apply each `ADD VALUE` in a separate migration.
ALTER TYPE "public"."Role" ADD VALUE 'PRODUCER';
ALTER TYPE "public"."Role" ADD VALUE 'HOST';
ALTER TYPE "public"."Role" ADD VALUE 'JUDGE';
ALTER TYPE "public"."Role" ADD VALUE 'CONTESTANT';

-- AlterEnum
-- NOTE: To support PostgreSQL 11 and earlier, apply each `ADD VALUE` in a separate migration.
ALTER TYPE "public"."QueueStatus" ADD VALUE 'APPROVED';
ALTER TYPE "public"."QueueStatus" ADD VALUE 'TOP_EIGHT';
ALTER TYPE "public"."QueueStatus" ADD VALUE 'SCORED';
ALTER TYPE "public"."QueueStatus" ADD VALUE 'REJECTED';
ALTER TYPE "public"."QueueStatus" ADD VALUE 'ELIMINATED';

-- AlterTable
ALTER TABLE "public"."queue_items" ADD COLUMN "cup_id" TEXT;

-- CreateTable
CREATE TABLE "public"."series" (
    "id" TEXT NOT NULL,
    "channel_id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "description" TEXT,
    "status" "public"."SeriesStatus" NOT NULL DEFAULT 'PLANNED',
    "starts_at" TIMESTAMP(3),
    "ends_at" TIMESTAMP(3),
    "metadata" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "series_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."cups" (
    "id" TEXT NOT NULL,
    "channel_id" TEXT NOT NULL,
    "series_id" TEXT,
    "title" TEXT NOT NULL,
    "slug" TEXT NOT NULL,
    "theme" TEXT,
    "status" "public"."CupStatus" NOT NULL DEFAULT 'DRAFT',
    "starts_at" TIMESTAMP(3),
    "ends_at" TIMESTAMP(3),
    "metadata" JSONB NOT NULL DEFAULT '{}'::jsonb,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "cups_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."channel_role_assignments" (
    "id" SERIAL NOT NULL,
    "channel_id" TEXT NOT NULL,
    "account_id" TEXT NOT NULL,
    "role" "public"."ShowRole" NOT NULL,
    "cup_id" TEXT,
    "assigned_by" TEXT,
    "expires_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "channel_role_assignments_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."judge_scores" (
    "id" SERIAL NOT NULL,
    "cup_id" TEXT NOT NULL,
    "queue_item_id" INTEGER NOT NULL,
    "judge_account_id" TEXT NOT NULL,
    "score" DECIMAL(12,5) NOT NULL,
    "comment" TEXT,
    "locked_at" TIMESTAMP(3),
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "judge_scores_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."cup_standings" (
    "id" SERIAL NOT NULL,
    "cup_id" TEXT NOT NULL,
    "channel_id" TEXT NOT NULL,
    "submitter_username" TEXT NOT NULL,
    "average_score" DECIMAL(12,5),
    "total_score" DECIMAL(12,5),
    "judge_count" INTEGER NOT NULL DEFAULT 0,
    "rank" INTEGER,
    "metadata" JSONB DEFAULT '{}'::jsonb,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "cup_standings_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "public"."series_standings" (
    "id" SERIAL NOT NULL,
    "series_id" TEXT NOT NULL,
    "channel_id" TEXT NOT NULL,
    "submitter_username" TEXT NOT NULL,
    "total_points" DECIMAL(12,5),
    "cups_played" INTEGER NOT NULL DEFAULT 0,
    "metadata" JSONB DEFAULT '{}'::jsonb,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP(3) NOT NULL,
    CONSTRAINT "series_standings_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "series_channel_id_slug_key" ON "public"."series"("channel_id", "slug");

-- CreateIndex
CREATE UNIQUE INDEX "cups_channel_id_slug_key" ON "public"."cups"("channel_id", "slug");

-- CreateIndex
CREATE UNIQUE INDEX "channel_role_assignments_channel_id_account_id_role_cup_id_key" ON "public"."channel_role_assignments"("channel_id", "account_id", "role", "cup_id");

-- CreateIndex
CREATE INDEX "judge_scores_judge_account_id_idx" ON "public"."judge_scores"("judge_account_id");

-- CreateIndex
CREATE UNIQUE INDEX "judge_scores_cup_id_queue_item_id_judge_account_id_key" ON "public"."judge_scores"("cup_id", "queue_item_id", "judge_account_id");

-- CreateIndex
CREATE INDEX "cup_standings_channel_id_idx" ON "public"."cup_standings"("channel_id");

-- CreateIndex
CREATE UNIQUE INDEX "cup_standings_cup_id_submitter_username_key" ON "public"."cup_standings"("cup_id", "submitter_username");

-- CreateIndex
CREATE INDEX "series_standings_channel_id_idx" ON "public"."series_standings"("channel_id");

-- CreateIndex
CREATE UNIQUE INDEX "series_standings_series_id_submitter_username_key" ON "public"."series_standings"("series_id", "submitter_username");

-- AddForeignKey
ALTER TABLE "public"."queue_items" ADD CONSTRAINT "queue_items_cup_id_fkey" FOREIGN KEY ("cup_id") REFERENCES "public"."cups"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."series" ADD CONSTRAINT "series_channel_id_fkey" FOREIGN KEY ("channel_id") REFERENCES "public"."channels"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."cups" ADD CONSTRAINT "cups_channel_id_fkey" FOREIGN KEY ("channel_id") REFERENCES "public"."channels"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."cups" ADD CONSTRAINT "cups_series_id_fkey" FOREIGN KEY ("series_id") REFERENCES "public"."series"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."channel_role_assignments" ADD CONSTRAINT "channel_role_assignments_channel_id_fkey" FOREIGN KEY ("channel_id") REFERENCES "public"."channels"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."channel_role_assignments" ADD CONSTRAINT "channel_role_assignments_account_id_fkey" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."channel_role_assignments" ADD CONSTRAINT "channel_role_assignments_cup_id_fkey" FOREIGN KEY ("cup_id") REFERENCES "public"."cups"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."channel_role_assignments" ADD CONSTRAINT "channel_role_assignments_assigned_by_fkey" FOREIGN KEY ("assigned_by") REFERENCES "public"."accounts"("id") ON DELETE SET NULL ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."judge_scores" ADD CONSTRAINT "judge_scores_cup_id_fkey" FOREIGN KEY ("cup_id") REFERENCES "public"."cups"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."judge_scores" ADD CONSTRAINT "judge_scores_queue_item_id_fkey" FOREIGN KEY ("queue_item_id") REFERENCES "public"."queue_items"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."judge_scores" ADD CONSTRAINT "judge_scores_judge_account_id_fkey" FOREIGN KEY ("judge_account_id") REFERENCES "public"."accounts"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."cup_standings" ADD CONSTRAINT "cup_standings_cup_id_fkey" FOREIGN KEY ("cup_id") REFERENCES "public"."cups"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."cup_standings" ADD CONSTRAINT "cup_standings_channel_id_fkey" FOREIGN KEY ("channel_id") REFERENCES "public"."channels"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."series_standings" ADD CONSTRAINT "series_standings_series_id_fkey" FOREIGN KEY ("series_id") REFERENCES "public"."series"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "public"."series_standings" ADD CONSTRAINT "series_standings_channel_id_fkey" FOREIGN KEY ("channel_id") REFERENCES "public"."channels"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
